export const articles = [
    {
        id: 1,
        title: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        subtitle:'PHOTOGRAPHY',
        subtitleTwo:'TRAVEL',
        url: `/img/img-one.jpg`,
    },
    {
        id: 2,
        title: 'Veniam, unde. Impedit qui laborum dolores perspiciatis enim nesciunt ullam deleniti error modi quo?',
        subtitle:'ART',
        subtitleTwo:'DESIGN',
        url: `/img/img-two.jpg`,
    },
    {
        id: 3,
        title: 'Sit sed deleniti soluta dolores ad ipsa dolorem, accusamus totam vero vitae amet.',
        subtitle:'PHOTOGRAPHY',
        subtitleTwo:'ART',
        url: `/img/img-three.jpg`,
    },
    {
        id: 4,
        title:'Iusto id nihil a, velit, voluptas aut quod hic labore!',
        subtitle:'TRAVEL',
        subtitleTwo:'OTHER',
        url: `/img/img-four.jpg`,
    },
    {
        id: 5,
        title:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        subtitle:'PRODUCT',
        subtitleTwo:'FURNITURE',
        url: `/img/img-five.jpg`,
    },
    {
        id: 6,
        title:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        subtitle:'ART',
        subtitleTwo:'OTHER',
        url: `/img/img-six.jpg`,
    },
    {
        id: 7,
        title:'Veniam, unde. Impedit qui laborum dolores perspiciatis enim nesciunt ullam deleniti error modi quo?',
        subtitle:'TRAVEL',
        subtitleTwo:'OTHER',
        url: `/img/img-seven.jpg`,
    },
    {
        id: 8,
        title:'Sit sed deleniti soluta dolores ad ipsa dolorem, accusamus totam vero vitae amet.',
        subtitle:'TRAVEL',
        subtitleTwo:'PRODUCT',
        url: `/img/img-eight.jpg`,
    },
    {
        id: 9,
        title:'Iusto id nihil a, velit, voluptas aut quod hic labore!',
        subtitle:'DESIGN',
        subtitleTwo:'PHOTOGRAPHY',
        url: `/img/img-nine.jpg`,
    },
    {
        id: 10,
        title:'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        subtitle:'PRODUCT',
        subtitleTwo:'FURNITURE',
        url: `/img/img-ten.jpg`,
    },
]

export const editorials = [
    {
        id: 1,
        title: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        subtitle:'ART',
        url: `/img/img-three.jpg`,
    },
    {
        id: 2,
        title: 'Veniam, unde. Impedit qui laborum dolores perspiciatis enim nesciunt ullam deleniti error modi quo?',
        subtitle:'OTHER',
        url: `/img/img-eight.jpg`,
    },
    {
        id: 3,
        title: 'Sit sed deleniti soluta dolores ad ipsa dolorem, accusamus totam vero vitae amet.',
        subtitle:'TRAVEL',
        url: `/img/img-four.jpg`,
    },
    {
        id: 4,
        title:'Iusto id nihil a, velit, voluptas aut quod hic labore!',
        subtitle:'DESIGN',
        url: `/img/img-nine.jpg`,
    },
]

export const conversations = [
    {
        id: 1,
        title: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        subtitle:'ART',
        subtitleTwo:'OTHER',
        url: `/img/img-three.jpg`,
    },
    {
        id: 2,
        title: 'Veniam, unde. Impedit qui laborum dolores perspiciatis enim nesciunt ullam deleniti error modi quo?',
        subtitle:'TRAVEL',
        subtitleTwo:'OTHER',
        url: `/img/img-seven.jpg`,
    },
]

export const artData = [
    {
        id: 1,
        title: 'Lorem Ipsum',
        artist: 'Firstname Lastname',
        subtitle:'ART',
        subtitleTwo:'OTHER',
        url: `/img/img-one.jpg`,
    },
    {
        id: 2,
        title: 'Dolor Sit Amet',
        artist: 'Firstname Lastname',
        subtitle:'TRAVEL',
        subtitleTwo:'OTHER',
        url: `/img/img-two.jpg`,
    },
    {
        id: 3,
        title: 'Ad Ipsa Dolorem',
        artist: 'Firstname Lastname',
        subtitle:'TRAVEL',
        subtitleTwo:'PRODUCT',
        url: `/img/img-three.jpg`,
    },
    {
        id: 4,
        title:'Iusto Id Nihil',
        artist: 'Firstname Lastname',
        subtitle:'DESIGN',
        subtitleTwo:'PHOTOGRAPHY',
        url: `/img/img-four.jpg`,
    },
    {
        id: 5,
        title:'Adipisicing Elit',
        artist: 'Firstname Lastname',
        subtitle:'PRODUCT',
        subtitleTwo:'FURNITURE',
        url: `/img/img-five.jpg`,
    },
    {
        id: 6,
        title:'Enim Nesciunt',
        artist: 'Firstname Lastname',
        subtitle:'ART',
        subtitleTwo:'OTHER',
        url: `/img/img-six.jpg`,
    },
    {
        id: 7,
        title:'Modi Quo',
        artist: 'Firstname Lastname',
        subtitle:'TRAVEL',
        subtitleTwo:'OTHER',
        url: `/img/img-seven.jpg`,
    },
    {
        id: 8,
        title:'Totam Vero Vitae',
        artist: 'Firstname Lastname',
        subtitle:'TRAVEL',
        subtitleTwo:'PRODUCT',
        url: `/img/img-eight.jpg`,
    },
    {
        id: 9,
        title:'Voluptas Labore!',
        artist: 'Firstname Lastname',
        subtitle:'DESIGN',
        subtitleTwo:'PHOTOGRAPHY',
        url: `/img/img-nine.jpg`,
    },
    {
        id: 10,
        title:'Lorem Ipsum',
        artist: 'Firstname Lastname',
        subtitle:'PRODUCT',
        subtitleTwo:'FURNITURE',
        url: `/img/img-ten.jpg`,
    },
]